//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsExp
{
    using System;
    using System.Collections.Generic;
    
    public partial class igi
    {
        public string Client { get; set; }
        public string Job_IDS { get; set; }
        public double Id { get; set; }
    }
}
