//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TsExp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheet
    {
        public string Date { get; set; }
        public string EmpId { get; set; }
        public string Name { get; set; }
        public string Reporting_Manager { get; set; }
        public string Product { get; set; }
        public string Client { get; set; }
        public string JobID { get; set; }
        public string Project { get; set; }
        public string Tasks { get; set; }
        public Nullable<int> No_of_Hours { get; set; }
        public int Id { get; set; }
    }
}
